inherit_mode:
  merge:
    - Exclude
    - Include
    - Prefixes

AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 3.1

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Metrics/ClassLength:
  CountAsOne:
    - array
    - hash
    - heredoc

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc

Metrics/ModuleLength:
  CountAsOne:
    - array
    - hash
    - heredoc

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
